[CmdletBinding(DefaultParameterSetName = 'Capture')]
param(
  [Parameter(ParameterSetName = 'Capture')]
  [string[]]$Id,

  [Parameter(ParameterSetName = 'Capture')]
  [switch]$All,

  [Parameter(ParameterSetName = 'List')]
  [switch]$List,

  [Parameter(ParameterSetName = 'Sync')]
  [switch]$SyncOnly
)

$ErrorActionPreference = 'Stop'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$repoRoot = [System.IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
$manifestPath = Join-Path $repoRoot 'work-images.json'
$mapPath = Join-Path $repoRoot 'work-images.js'
$captureRoot = Join-Path $repoRoot '.capture'
$stageRoot = Join-Path $captureRoot 'stage'
$profileRoot = Join-Path $captureRoot 'profiles'
$outputRoot = Join-Path $repoRoot 'img\works'

function Assert-UnderRoot([string]$Path, [string]$Root, [string]$Label) {
  $resolvedPath = [System.IO.Path]::GetFullPath($Path)
  $resolvedRoot = [System.IO.Path]::GetFullPath($Root).TrimEnd('\') + '\'
  if (-not $resolvedPath.StartsWith($resolvedRoot, [System.StringComparison]::OrdinalIgnoreCase)) {
    throw "$Label is outside the allowed root: $resolvedPath"
  }
  return $resolvedPath
}

function Find-Browser {
  $candidates = @(
    "${env:ProgramFiles(x86)}\Microsoft\Edge\Application\msedge.exe",
    "${env:ProgramFiles}\Microsoft\Edge\Application\msedge.exe",
    "${env:ProgramFiles}\Google\Chrome\Application\chrome.exe",
    "${env:LOCALAPPDATA}\Google\Chrome\Application\chrome.exe"
  )
  foreach ($candidate in $candidates) {
    if ($candidate -and (Test-Path -LiteralPath $candidate -PathType Leaf)) {
      return [System.IO.Path]::GetFullPath($candidate)
    }
  }
  throw 'Microsoft Edge or Google Chrome was not found.'
}

function Write-ImageMap($Manifest) {
  $map = [ordered]@{}
  foreach ($work in $Manifest.works) {
    $imagePath = Join-Path $repoRoot ([string]$work.image -replace '/', '\')
    if (-not (Test-Path -LiteralPath $imagePath -PathType Leaf)) { continue }
    $record = [ordered]@{ src = [string]$work.image; alt = [string]$work.alt }
    $keys = @([string]$work.id) + @($work.aliases)
    foreach ($key in $keys) {
      if ($key) { $map[$key] = $record }
    }
  }
  $json = $map | ConvertTo-Json -Depth 5 -Compress
  $script = @"
// Generated by scripts/capture-work-images.ps1 from work-images.json.
// Do not edit this file by hand.
globalThis.WORK_IMAGES = $json;

(() => {
  const addFallbackImages = () => {
    for (const [id, image] of Object.entries(globalThis.WORK_IMAGES || {})) {
      const entry = document.getElementById(id);
      if (!entry || !entry.matches('details.entry') || entry.querySelector('.media-group img, .media-group video')) continue;
      const body = entry.querySelector(':scope > .body');
      if (!body) continue;
      const group = document.createElement('div');
      group.className = 'media-group generated-work-image';
      const img = document.createElement('img');
      img.className = 'media';
      img.src = image.src;
      img.alt = image.alt || '';
      img.loading = 'lazy';
      img.decoding = 'async';
      group.appendChild(img);
      body.insertBefore(group, body.querySelector(':scope > .outlinks'));
    }
  };
  if (document.querySelector('details.entry')) addFallbackImages();
  else if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', addFallbackImages, { once: true });
  else addFallbackImages();
})();
"@
  [System.IO.File]::WriteAllText($mapPath, $script, [System.Text.UTF8Encoding]::new($false))
  Write-Host "Synced $($map.Count) image keys to work-images.js"
}

if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
  throw "Manifest not found: $manifestPath"
}
$manifest = Get-Content -LiteralPath $manifestPath -Raw | ConvertFrom-Json

if ($List) {
  $manifest.works | ForEach-Object {
    $imagePath = Join-Path $repoRoot ([string]$_.image -replace '/', '\')
    [pscustomobject]@{
      Id = $_.id
      Image = $_.image
      Exists = Test-Path -LiteralPath $imagePath -PathType Leaf
      Mode = if ($_.capture) { 'capture' } elseif ($_.skipReason) { 'skip' } else { 'reuse' }
      Note = $_.skipReason
    }
  } | Format-Table -AutoSize
  exit 0
}

if ($SyncOnly) {
  Write-ImageMap $manifest
  exit 0
}

if (-not $All -and (-not $Id -or $Id.Count -eq 0)) {
  throw 'Choose -All or at least one -Id. Use -List to inspect targets.'
}

$targets = @($manifest.works | Where-Object {
  $_.capture -and ($All -or $Id -contains [string]$_.id)
})
if ($targets.Count -eq 0) {
  throw 'No capture targets matched.'
}

if (-not (Test-Path -LiteralPath $captureRoot)) { [void][System.IO.Directory]::CreateDirectory($captureRoot) }
if (-not (Test-Path -LiteralPath $stageRoot)) { [void][System.IO.Directory]::CreateDirectory($stageRoot) }
if (-not (Test-Path -LiteralPath $profileRoot)) { [void][System.IO.Directory]::CreateDirectory($profileRoot) }
if (-not (Test-Path -LiteralPath $outputRoot)) { [void][System.IO.Directory]::CreateDirectory($outputRoot) }

$browser = Find-Browser
$width = [int]$manifest.defaults.width
$height = [int]$manifest.defaults.height
$results = [System.Collections.Generic.List[object]]::new()

Add-Type -AssemblyName System.Drawing

foreach ($work in $targets) {
  $started = Get-Date
  $idValue = [string]$work.id
  $result = [ordered]@{ id = $idValue; status = 'failed'; url = [string]$work.capture.url; output = [string]$work.image; elapsedMs = 0; message = '' }
  try {
    if ($idValue -notmatch '^[a-z0-9]+(?:-[a-z0-9]+)*$') { throw "Unsafe work id: $idValue" }
    $outputPath = Assert-UnderRoot (Join-Path $repoRoot ([string]$work.image -replace '/', '\')) $outputRoot 'Output image'
    $stagePng = Assert-UnderRoot (Join-Path $stageRoot "$idValue.png") $stageRoot 'Staged screenshot'
    $stageJpg = Assert-UnderRoot (Join-Path $stageRoot "$idValue.jpg") $stageRoot 'Staged JPEG'
    $waitMs = if ($work.capture.waitMs) { [int]$work.capture.waitMs } else { [int]$manifest.defaults.waitMs }
    if ($waitMs -lt 0 -or $waitMs -gt 15000) { throw "waitMs must be between 0 and 15000 for $idValue" }
    $processTimeoutMs = if ($work.capture.processTimeoutMs) { [int]$work.capture.processTimeoutMs } else { 45000 }
    if ($processTimeoutMs -lt 5000 -or $processTimeoutMs -gt 60000) { throw "processTimeoutMs must be between 5000 and 60000 for $idValue" }

    $renderUrl = if ($work.capture.localUrl) { [string]$work.capture.localUrl } else { [string]$work.capture.url }
    $result.renderUrl = $renderUrl
    $curl = Get-Command 'curl.exe' -ErrorAction SilentlyContinue
    if (-not $curl) { throw 'curl.exe was not found for URL preflight.' }
    $httpCode = & $curl.Source -sS -L --max-time 20 -o NUL -w '%{http_code}' -- $renderUrl
    if ($LASTEXITCODE -ne 0) {
      Write-Warning "URL preflight could not run (curl exit code $LASTEXITCODE); continuing with browser capture."
    }
    else {
      $statusCode = 0
      if (-not [int]::TryParse(([string]$httpCode).Trim(), [ref]$statusCode)) {
        throw "URL preflight returned an invalid status: $httpCode"
      }
      if ($statusCode -lt 200 -or $statusCode -ge 400) {
        throw "URL preflight returned HTTP $statusCode."
      }
    }

    if (Test-Path -LiteralPath $stagePng -PathType Leaf) { [System.IO.File]::Delete($stagePng) }
    if (Test-Path -LiteralPath $stageJpg -PathType Leaf) { [System.IO.File]::Delete($stageJpg) }

    $profilePath = Assert-UnderRoot (Join-Path $profileRoot $idValue) $profileRoot 'Browser profile'
    if (-not (Test-Path -LiteralPath $profilePath)) { [void][System.IO.Directory]::CreateDirectory($profilePath) }
    $arguments = @(
      '--headless=new',
      '--disable-logging',
      '--log-level=3',
      '--hide-scrollbars',
      '--run-all-compositor-stages-before-draw',
      "--window-size=$width,$height",
      "--virtual-time-budget=$waitMs",
      "--user-data-dir=$profilePath",
      "--screenshot=$stagePng",
      $renderUrl
    )

    $browserProcess = Start-Process -FilePath $browser -ArgumentList $arguments -WindowStyle Hidden -PassThru
    $forcedClose = $false
    if (-not $browserProcess.WaitForExit($processTimeoutMs)) {
      Stop-Process -Id $browserProcess.Id -Force -ErrorAction SilentlyContinue
      $forcedClose = $true
    }
    $deadline = (Get-Date).AddSeconds(15)
    while (-not (Test-Path -LiteralPath $stagePng -PathType Leaf) -and (Get-Date) -lt $deadline) {
      Start-Sleep -Milliseconds 250
    }
    if (-not (Test-Path -LiteralPath $stagePng -PathType Leaf)) { throw 'Browser did not produce a screenshot.' }

    $bitmap = [System.Drawing.Image]::FromFile($stagePng)
    $encoderParams = $null
    $outputBitmap = $null
    $outputGraphics = $null
    try {
      if ($bitmap.Width -ne $width -or $bitmap.Height -ne $height) {
        throw "Unexpected dimensions: $($bitmap.Width)x$($bitmap.Height)"
      }
      $imageToSave = $bitmap
      if ($work.capture.crop) {
        $cropX = [int]$work.capture.crop.x
        $cropY = [int]$work.capture.crop.y
        $cropWidth = [int]$work.capture.crop.width
        $cropHeight = [int]$work.capture.crop.height
        if ($cropX -lt 0 -or $cropY -lt 0 -or $cropWidth -lt 1 -or $cropHeight -lt 1 -or
            ($cropX + $cropWidth) -gt $bitmap.Width -or ($cropY + $cropHeight) -gt $bitmap.Height -or
            ([math]::Abs(($cropWidth / $cropHeight) - ($width / $height))) -gt 0.01) {
          throw "Invalid 4:3 crop for $idValue"
        }
        $outputBitmap = [System.Drawing.Bitmap]::new($width, $height)
        $outputGraphics = [System.Drawing.Graphics]::FromImage($outputBitmap)
        $destination = [System.Drawing.Rectangle]::new(0, 0, $width, $height)
        $source = [System.Drawing.Rectangle]::new($cropX, $cropY, $cropWidth, $cropHeight)
        $outputGraphics.DrawImage($bitmap, $destination, $source, [System.Drawing.GraphicsUnit]::Pixel)
        $imageToSave = $outputBitmap
      }
      $codec = [System.Drawing.Imaging.ImageCodecInfo]::GetImageEncoders() | Where-Object MimeType -eq 'image/jpeg' | Select-Object -First 1
      $quality = [System.Drawing.Imaging.Encoder]::Quality
      $encoderParams = [System.Drawing.Imaging.EncoderParameters]::new(1)
      $encoderParams.Param[0] = [System.Drawing.Imaging.EncoderParameter]::new($quality, [long]86)
      $imageToSave.Save($stageJpg, $codec, $encoderParams)
    }
    finally {
      if ($outputGraphics) { $outputGraphics.Dispose() }
      if ($outputBitmap) { $outputBitmap.Dispose() }
      $bitmap.Dispose()
      if ($encoderParams) { $encoderParams.Dispose() }
    }
    if ((Get-Item -LiteralPath $stageJpg).Length -lt 12000) { throw 'JPEG is suspiciously small.' }

    [System.IO.File]::Copy($stageJpg, $outputPath, $true)
    $result.status = 'captured'
    $result.message = "$(Get-Item -LiteralPath $outputPath | ForEach-Object Length) bytes$(if ($forcedClose) { '; browser closed after screenshot' })"
  }
  catch {
    $result.message = $_.Exception.Message
  }
  finally {
    $result.elapsedMs = [int]((Get-Date) - $started).TotalMilliseconds
    $results.Add([pscustomobject]$result)
  }
}

Write-ImageMap $manifest
$reportPath = Assert-UnderRoot (Join-Path $captureRoot 'report.json') $captureRoot 'Capture report'
[System.IO.File]::WriteAllText($reportPath, ($results | ConvertTo-Json -Depth 5), [System.Text.UTF8Encoding]::new($false))
$results | Format-Table id, status, elapsedMs, output, message -AutoSize

if (@($results | Where-Object status -eq 'failed').Count -gt 0) { exit 1 }
