/* Lift slides from one portfolio cut into another.

   A cut is a sequence of pages, most of which already exist on another route.
   Copying them by hand loses a folio number or a media path every time, so this
   does it: it reads a plan, pulls each named page out of its source route's
   slides.html whole, rewrites the media paths so they still resolve from the new
   folder, renumbers the folios into the new order, and writes one slides.html.

   Authored pages — a cover, a page for a work no route carries yet — are named
   in the plan with a `file` instead of a source, and are copied in verbatim.

       node xyhtamura.github.io/scripts/lift-slides.mjs xyhtamura.github.io/pfm/plan.json

   Run it from F:\xyh. Paths in the plan are relative to the plan's own folder.
   The output is overwritten each run, so the plan is the thing to edit, not the
   slides.html it produces. Verify with scripts/audit-cuts.mjs afterwards. */

import fs from "node:fs";
import path from "node:path";

const planPath = process.argv[2];
if (!planPath) {
  console.error("usage: node lift-slides.mjs <plan.json>");
  process.exit(1);
}

const planDir = path.dirname(path.resolve(planPath));
const plan = JSON.parse(fs.readFileSync(planPath, "utf8"));
const siteDir = path.resolve("xyhtamura.github.io");
const sources = new Map();

function sourceSlides(route) {
  if (!sources.has(route)) {
    const file = path.join(siteDir, route, "slides.html");
    sources.set(route, fs.readFileSync(file, "utf8"));
  }
  return sources.get(route);
}

/* Splits a slides.html into whole <section class="page…"> … </section> blocks.
   The documents nest no sections, so a scan for the closing tag is exact. */
function sections(html) {
  const found = [];
  const open = /<section class="page[^"]*"[^>]*>/g;
  let match;
  while ((match = open.exec(html)) !== null) {
    const end = html.indexOf("</section>", match.index);
    if (end === -1) throw new Error("unclosed <section> in source");
    found.push(html.slice(match.index, end + "</section>".length));
  }
  return found;
}

/* The year rides inside the heading as its own span, the way the engine's own
   headingName() expects; drop it before matching, or a plan would have to name
   the year to find the page. */
function headingOf(section) {
  const match = section.match(/<h[12][^>]*>([\s\S]*?)<\/h[12]>/);
  if (!match) return "";
  return match[1]
    .replace(/<span class="year">[\s\S]*?<\/span>/g, "")
    .replace(/<[^>]*>/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

/* A lifted page keeps its slot ids, alt text and credits; only the two things
   that are true of its position change — where its pictures live, and which
   number the folio prints. */
function rewriteMedia(section, route) {
  return section.replace(/(src|data-src)="media\//g, `$1="../${route}/media/`);
}

function renumberFolio(section, page) {
  return section.replace(
    /(<div class="folio"><span>[^<]*<\/span><span>)[^<]*(<\/span><\/div>)/,
    `$1${page}$2`
  );
}

const out = [];
plan.pages.forEach((entry, index) => {
  const page = index + 1;

  if (entry.file) {
    const authored = fs.readFileSync(path.join(planDir, entry.file), "utf8").trim();
    out.push(renumberFolio(authored, page));
    console.log(`${String(page).padStart(2, "0")}  authored  ${entry.file}`);
    return;
  }

  const wanted = entry.heading.toLowerCase();
  const candidates = sections(sourceSlides(entry.from));
  const found = candidates.find((section) => headingOf(section).toLowerCase() === wanted);
  if (!found) {
    console.error(`page ${page}: no slide titled "${entry.heading}" in ${entry.from}`);
    process.exit(1);
  }

  out.push(renumberFolio(rewriteMedia(found, entry.from), page));
  const pictures = (found.match(/<img /g) || []).length;
  console.log(`${String(page).padStart(2, "0")}  ${entry.from}  ${entry.heading} (${pictures} pictures)`);
});

const header = `<!-- ${plan.title}\n     Generated by scripts/lift-slides.mjs from plan.json. Edit the plan, or the\n     authored pages it names, and run it again. -->\n\n`;
const outPath = path.join(planDir, plan.out || "slides.html");
fs.writeFileSync(outPath, header + out.join("\n\n") + "\n");
console.log(`\n${outPath} — ${out.length} slides`);
